### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by randomouscrap98** [randomouscrap98/bbscope-rust#1]
The \<br> isn't displaying, the section explaining [code] just stops mid sentence, the [\*] disappears in the list thing

**Comment by justinacolmena** [comment]
Not really sure where to go on this, but to actually display the BBCode in the browser..
```rust
#[macro_use] extern crate rocket;

use rocket::response::content;
use bbscope::BBCode;


#[get("/")]
fn index() -> content::RawHtml<String> {
   content::RawHtml(BBCode::default().unwrap()
   .parse(&("[b]bbscope 0.0.6:[/b] ".to_owned()
   + "[url=https://docs.rs/bbscope/0.0.6/bbscope/]docs[/url]")))
}

#[launch]
fn rocket() -> _ {
    rocket::build()
    .mount("/", routes![index])
}
```
![bbscope](https://user-images.githubusercontent.com/32494761/208237161-bab41a8a-7a06-4cc0-b71d-73d9c787b9cb.png)

**Comment by randomouscrap98** [comment]
Hey that's a good idea, I went ahead and added a rocket example. You should reuse the bbcode instance you create, so I added it as state in the rocket setup.

**Comment by justinacolmena** [comment]
So this "bbcode" parser stuff is mostly old-school. Straight off the train with a suitcase. That reusable instance with the "unwrap()" routine was a lot of big code back in the day.

https://www.ibm.com/docs/en/zos/2.4.0?topic=works-yyparse-yylex

And that was all reworked much later by Richard Stallman into "bison" and "flex" for the the "GNU" project in the "C" programming language, and now Stallman is passed away, too.
