### ISSUE TITLE
ScopeInfo::basic is private

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [randomouscrap98/bbscope-rust#4]
`ScopeInfo::basic` is mentioned in the readme, and its doc comment mentions "a highly common case, you probably want this". However users can't use it, because it's not `pub`.

**Comment by randomouscrap98** [comment]
Huh, that's kind of silly. I can certainly fix it, give me a bit (I hope you haven't been waiting on this, I'm sorry!).

**Comment by ColonelThirtyTwo** [comment]
It's not too difficult to construct the equivalent ScopeInfo, so it's not a blocker, but it is a bit of a gotcha.

**Comment by randomouscrap98** [comment]
Thank you for letting me know; I feel weird sending an update with just one little thing, so I did a bit of a refactor to fix several issues I saw people having. I hope it's not bothersome to have the fix be behind a bit of an API change.
